name = "my-daily-worker"
main = "src/index.ts"
compatibility_date = "2024-05-01"
workers_dev = false

[vars]
MY_DAILY_FROM_EMAIL = "hello@liuallen.com"
MY_DAILY_REPLY_DOMAIN = "liuallen.com"

[[d1_databases]]
binding = "DB"
database_name = "my-daily"
database_id = "4848415a-82da-42ff-8b90-01c5275b5d22"

[triggers]
crons = ["*/5 * * * *"]

